"""timeline added to db

Revision ID: 051a4c14615b
Revises: ba739dff5f7f
Create Date: 2024-03-11 21:10:47.962689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051a4c14615b'
down_revision = 'ba739dff5f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeline', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('timeline')

    # ### end Alembic commands ###
