"""fix: rename usermodel to user

Revision ID: 2c9b5c10a0c7
Revises: 
Create Date: 2023-10-02 15:41:16.053155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9b5c10a0c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('profile_pic', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_model_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_model_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('name', sa.String(length=128), server_default='default', nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variable')
    op.drop_table('function')
    op.drop_table('module')
    op.drop_table('user')
    # ### end Alembic commands ###
