"""change timeline format

Revision ID: 49a7bf3cd2ea
Revises: 051a4c14615b
Create Date: 2024-03-12 20:58:49.624962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '49a7bf3cd2ea'
down_revision = '051a4c14615b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('timeline',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=20000),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('timeline',
               existing_type=sa.String(length=20000),
               type_=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
