"""allow timeline to be null

Revision ID: 4fc1bf1500f5
Revises: 49a7bf3cd2ea
Create Date: 2024-03-12 21:04:11.829716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc1bf1500f5'
down_revision = '49a7bf3cd2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('timeline',
               existing_type=sa.VARCHAR(length=20000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('timeline',
               existing_type=sa.VARCHAR(length=20000),
               nullable=False)

    # ### end Alembic commands ###
